<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ApplicationIcon>wwwroot\photino-logo.ico</ApplicationIcon>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PublishTrimmed>False</PublishTrimmed>
    <PublishAot>False</PublishAot>
    <Platforms>AnyCPU;x64;ARM64</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(PhotinoX_UseLocalProjects)' == 'true'">
    <OSPlatform Condition="$([MSBuild]::IsOSPlatform('Windows'))">Windows</OSPlatform>
    <OSPlatform Condition="$([MSBuild]::IsOSPlatform('OSX'))">OSX</OSPlatform>
    <OSPlatform Condition="$([MSBuild]::IsOSPlatform('Linux'))">Linux</OSPlatform>
  </PropertyGroup>

  <PropertyGroup Condition="'$(PhotinoX_UseLocalProjects)' == 'true'">
    <DefineConstants>$(DefineConstants);UseLocalProjects</DefineConstants>
    <PhotinoNetSourceDir Condition="'$(PhotinoNetSourceDir)' == ''">..\..\PhotinoX\Photino.NET</PhotinoNetSourceDir>
  </PropertyGroup>

  <ItemGroup Condition="'$(PhotinoX_UseLocalProjects)' == 'true'">
    <Compile Include="$(PhotinoNetSourceDir)\Extensions.cs" Link="Extensions.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\Platform.cs" Link="Platform.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\Platform.Linux.cs" Link="Platform.Linux.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\Platform.MacOS.cs" Link="Platform.MacOS.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\PhotinoDialogEnums.cs" Link="PhotinoDialogEnums.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\NativeMethods.cs" Link="NativeMethods.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\NativeMethods.Application.cs" Link="NativeMethods.Application.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\NativeMethods.Browser.cs" Link="NativeMethods.Browser.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\NativeMethods.Dialogs.cs" Link="NativeMethods.Dialogs.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\NativeMethods.Memory.cs" Link="NativeMethods.Memory.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\NativeMethods.Notifications.cs" Link="NativeMethods.Notifications.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\NativeMethods.Window.cs" Link="NativeMethods.Window.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\PhotinoMonitorStruct.cs" Link="PhotinoMonitorStruct.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\NativeDelegates.cs" Link="NativeDelegates.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\PhotinoApplication.cs" Link="PhotinoApplication.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\PhotinoApplication.Enums.cs" Link="PhotinoApplication.Enums.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\PhotinoApplication.EventArgs.cs" Link="PhotinoApplication.EventArgs.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\PhotinoApplication.Events.cs" Link="PhotinoApplication.Events.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\PhotinoApplication.Fluent.cs" Link="PhotinoApplication.Fluent.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\PhotinoApplication.Helpers.cs" Link="PhotinoApplication.Helpers.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\PhotinoApplication.NativeParameters.cs" Link="PhotinoApplication.NativeParameters.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\PhotinoApplication.Notifications.cs" Link="PhotinoApplication.Notifications.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\PhotinoBootstrap.cs" Link="PhotinoBootstrap.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\PhotinoDispatcher.cs" Link="PhotinoDispatcher.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\PhotinoDispatcher.States.cs" Link="PhotinoDispatcher.States.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\PhotinoWindow.CustomSchemes.cs" Link="PhotinoWindow.CustomSchemes.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\PhotinoWindow.Dialogs.cs" Link="PhotinoWindow.Dialogs.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\PhotinoWindow.Events.cs" Link="PhotinoWindow.Events.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\PhotinoWindow.Extensions.cs" Link="PhotinoWindow.Extensions.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\PhotinoWindow.Fluent.cs" Link="PhotinoWindow.Fluent.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\PhotinoWindow.Fluent.Handlers.cs" Link="PhotinoWindow.Fluent.Handlers.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\PhotinoWindow.NativeParameters.cs" Link="PhotinoNativeWindow.Parameters.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\PhotinoWindow.Helpers.cs" Link="PhotinoWindow.Helpers.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\PhotinoWindow.States.cs" Link="PhotinoWindow.States.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\PhotinoWindow.cs" Link="PhotinoWindow.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\PhotinoWindowCollection.cs" Link="PhotinoWindowCollection.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\PhotinoWindow.Enums.cs" Link="PhotinoWindow.Enums.cs" />
    <Compile Include="$(PhotinoNetSourceDir)\PhotinoWindow.EventArgs.cs" Link="PhotinoWindow.EventArgs.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Update="wwwroot\main.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="wwwroot\chromeless.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="wwwroot\photino-logo.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="wwwroot\photino-logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <PropertyGroup Condition="'$(PhotinoX_UseLocalProjects)' == 'true' AND '$(OSPlatform)' == 'Windows'">
    <NativePlatform Condition="'$(Platform)' == 'x64'">x64</NativePlatform>
    <NativePlatform Condition="'$(Platform)' == 'ARM64'">ARM64</NativePlatform>
    <NativePlatform Condition="'$(Platform)' == 'AnyCPU' OR '$(Platform)' == ''">x64</NativePlatform>

    <NativeRidArch Condition="'$(NativePlatform)' == 'x64'">x64</NativeRidArch>
    <NativeRidArch Condition="'$(NativePlatform)' == 'ARM64'">arm64</NativeRidArch>

    <NativeProjectPath>$(MSBuildProjectDirectory)/../Photino.Native/Photino.Native.vcxproj</NativeProjectPath>
    <NativeOutputDir>$(MSBuildProjectDirectory)/../Photino.Native/$(NativePlatform)/$(Configuration)/</NativeOutputDir>
  </PropertyGroup>

  <Target Name="ValidatePhotinoNetSourceDir"
          BeforeTargets="BeforeBuild"
          Condition="'$(PhotinoX_UseLocalProjects)' == 'true'
                 AND '$(DesignTimeBuild)' != 'true'">
    <Error
      Text="PhotinoNetSourceDir does not exist or does not contain PhotinoWindow.cs: $(PhotinoNetSourceDir)"
      Condition="!Exists('$(PhotinoNetSourceDir)\PhotinoWindow.cs')" />
  </Target>

  <Target Name="Photino_BuildNativeWindows"
          BeforeTargets="DispatchToInnerBuilds"
          Condition="'$(PhotinoX_UseLocalProjects)' == 'true'
                 AND '$(OSPlatform)' == 'Windows'
                 AND '$(NativePlatform)' != ''
                 AND '$(IsCrossTargetingBuild)' == 'true'
                 AND '$(DesignTimeBuild)' != 'true'">

    <Error
      Text="Native project not found: $(NativeProjectPath)"
      Condition="!Exists('$(NativeProjectPath)')" />

    <Message Importance="High"
             Text="Building native project '$(NativeProjectPath)' for $(Configuration)|$(NativePlatform)" />

    <MSBuild
      Projects="$(NativeProjectPath)"
      Targets="Build"
      Properties="Configuration=$(Configuration);Platform=$(NativePlatform)" />
  </Target>

  <Target Name="Photino_CopyNativeLibs_Windows"
          AfterTargets="Build"
          Condition="'$(PhotinoX_UseLocalProjects)' == 'true'
                 AND '$(OSPlatform)' == 'Windows'
                 AND '$(NativePlatform)' != ''
                 AND '$(TargetFramework)' != ''
                 AND '$(DesignTimeBuild)' != 'true'">

    <Message Importance="High"
             Text="Copying native libs from '$(NativeOutputDir)' to '$(TargetDir)'" />

    <Error
      Text="Native library not found: $(NativeOutputDir)PhotinoX.Native.dll"
      Condition="!Exists('$(NativeOutputDir)PhotinoX.Native.dll')" />

    <Copy
      SourceFiles="$(NativeOutputDir)PhotinoX.Native.dll"
      DestinationFiles="$(TargetDir)PhotinoX.Native.dll"
      SkipUnchangedFiles="true" />

    <Copy
      SourceFiles="$(NativeOutputDir)PhotinoX.Native.pdb"
      DestinationFiles="$(TargetDir)PhotinoX.Native.pdb"
      SkipUnchangedFiles="true"
      Condition="'$(Configuration)' == 'Debug'
             AND Exists('$(NativeOutputDir)PhotinoX.Native.pdb')" />

    <Copy
      SourceFiles="$(NativeOutputDir)runtimes/win-$(NativeRidArch)/native/WebView2Loader.dll"
      DestinationFiles="$(TargetDir)WebView2Loader.dll"
      SkipUnchangedFiles="true"
      Condition="Exists('$(NativeOutputDir)runtimes/win-$(NativeRidArch)/native/WebView2Loader.dll')" />
  </Target>

  <PropertyGroup Condition="'$(PhotinoX_UseLocalProjects)' == 'true' AND '$(OSPlatform)' == 'OSX'">
    <NativeOutputDir>$(MSBuildProjectDirectory)/../lib/x64/</NativeOutputDir>
  </PropertyGroup>

  <Target Name="Photino_CopyNativeLibs_OSX"
          AfterTargets="Build"
          Condition="'$(PhotinoX_UseLocalProjects)' == 'true'
               AND '$(OSPlatform)' == 'OSX'
               AND '$(TargetFramework)' != ''
               AND '$(DesignTimeBuild)' != 'true'">

    <Message Importance="High"
             Text="Copying native libs from '$(NativeOutputDir)' to '$(TargetDir)'" />

    <Error
      Text="Native library not found: $(NativeOutputDir)PhotinoX.Native.dylib"
      Condition="!Exists('$(NativeOutputDir)PhotinoX.Native.dylib')" />

    <Copy
      SourceFiles="$(NativeOutputDir)PhotinoX.Native.dylib"
      DestinationFiles="$(TargetDir)PhotinoX.Native.dylib"
      SkipUnchangedFiles="true" />
  </Target>

  <PropertyGroup Condition="'$(PhotinoX_UseLocalProjects)' == 'true' AND '$(OSPlatform)' == 'Linux'">
    <HostArchitecture>$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)</HostArchitecture>

    <NativePlatform Condition="'$(Platform)' == 'x64'">x64</NativePlatform>
    <NativePlatform Condition="'$(Platform)' == 'ARM64'">arm64</NativePlatform>

    <NativePlatform Condition="('$(Platform)' == 'AnyCPU' OR '$(Platform)' == '') AND '$(HostArchitecture)' == 'Arm64'">arm64</NativePlatform>
    <NativePlatform Condition="('$(Platform)' == 'AnyCPU' OR '$(Platform)' == '') AND '$(HostArchitecture)' == 'X64'">x64</NativePlatform>

    <NativePlatform Condition="'$(NativePlatform)' == ''">x64</NativePlatform>

    <NativeOutputDir>$(MSBuildProjectDirectory)/../lib/$(NativePlatform)/</NativeOutputDir>
  </PropertyGroup>

  <Target Name="Photino_CopyNativeLibs_Linux"
          AfterTargets="Build"
          Condition="'$(PhotinoX_UseLocalProjects)' == 'true'
               AND '$(OSPlatform)' == 'Linux'
               AND '$(NativePlatform)' != ''
               AND '$(TargetFramework)' != ''
               AND '$(DesignTimeBuild)' != 'true'">

    <Message Importance="High"
             Text="Copying native libs from '$(NativeOutputDir)' to '$(TargetDir)'" />

    <Error
      Text="Native library not found: $(NativeOutputDir)PhotinoX.Native.so"
      Condition="!Exists('$(NativeOutputDir)PhotinoX.Native.so')" />

    <Copy
      SourceFiles="$(NativeOutputDir)PhotinoX.Native.so"
      DestinationFiles="$(TargetDir)PhotinoX.Native.so"
      SkipUnchangedFiles="true" />
  </Target>

</Project>
